/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Outlet,
  Pipe,
  Pluck,
} from 'plumbing-toolkit';
import {
  SinkMode,
} from './types';

export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface PipeSink {
    'clearOnUpdate': boolean;
    'connect'?: (outlet: Outlet<any>, pipe?: Pipe<any>) => Pluck;
    'mode': SinkMode;
    'pipe'?: Pipe<any>;
    'pluck': () => Promise<void>;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPipeSinkElement extends Components.PipeSink, HTMLStencilElement {}
  var HTMLPipeSinkElement: {
    prototype: HTMLPipeSinkElement;
    new (): HTMLPipeSinkElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'pipe-sink': HTMLPipeSinkElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface PipeSink {
    'clearOnUpdate'?: boolean;
    'connect'?: (outlet: Outlet<any>, pipe?: Pipe<any>) => Pluck;
    'mode'?: SinkMode;
    'pipe'?: Pipe<any>;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'pipe-sink': PipeSink;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'pipe-sink': LocalJSX.PipeSink & JSXBase.HTMLAttributes<HTMLPipeSinkElement>;
    }
  }
}


